build:
  image: node:4.2
  commands:
    - make install
    - make test

publish:
  # coverage:
  #   # Must match parts of the absolute path
  #   include: drone-nuget/coverage/lcov.info
  #   when:
  #     branch: master
  docker:
    registry: registry.cd.pf-labs.net
    repo: drone-plugins/nuget
    file: Dockerfile
    email: "dev@peoplefluent.com"
    tag:
      - latest
      - "0.0.$$BUILD_NUMBER"
      - "$${COMMIT:0:9}"
    when:
      branch: master

# The below section is used to advertise the plugin on the drone website
# plugin:
#   name: NuGet
#   desc: Publish files and artifacts to NuGet repository
#   type: publish
#   image: plugins/drone-nuget
#   labels:
#     - nuget
